// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJllDrABP3ZDH4WDmuiSHNAbHBkZdnp_0',
    appId: '1:229876668324:web:f4d588922f2c098a5c5331',
    messagingSenderId: '229876668324',
    projectId: 'newsapp-bc6ee',
    authDomain: 'newsapp-bc6ee.firebaseapp.com',
    storageBucket: 'newsapp-bc6ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4hTckeKBx2n0kdGHATchMOgURodTpZuk',
    appId: '1:229876668324:android:74d365dbe572b1fb5c5331',
    messagingSenderId: '229876668324',
    projectId: 'newsapp-bc6ee',
    storageBucket: 'newsapp-bc6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7DS-bsmU8sdatCWUKMInXTn0p1q8tTQ',
    appId: '1:229876668324:ios:bee424808871fa245c5331',
    messagingSenderId: '229876668324',
    projectId: 'newsapp-bc6ee',
    storageBucket: 'newsapp-bc6ee.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7DS-bsmU8sdatCWUKMInXTn0p1q8tTQ',
    appId: '1:229876668324:ios:065cad7cd3191dc05c5331',
    messagingSenderId: '229876668324',
    projectId: 'newsapp-bc6ee',
    storageBucket: 'newsapp-bc6ee.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
